config/routes.rb
Rails.application.routes.draw do
  devise_for :profiles
  resources :ads
  resources :rubrics
  resources :properts
  get 'info/socket'

  get 'info/convention'

  get 'info/offer'

  root 'index#index'

  resources :cities

end

app/views/inc/_footer.html.slim
footer.navbar-default
  ul.nav.nav-justified
    li
      a href=new_ad_url Подать объявление
    li
      a href=root_url Объявления
    li
      a href="#" Помощь
    li
      a href="#" Безопасность
    li
      a href="#" Реклама на сайте
    li
      a href="#" О компании
  .text-justify
    p
      | ©
      =InfoHelper::NAME_SITE
      |  — сайт объявлений. Использование сайта, в том числе подача объявлений, означает согласие с
      a[href=info_convention_path]  пользовательским соглашением.
      |  Оплачивая услуги на сайте, вы принимаете
      a[href=info_offer_url]  оферту
      |.

app/views/inc/_header.html.slim
nav.navbar-default
  .row
      .col-xs-12.col-sm-12.col-md-12.col-lg-12
        = form_tag("/search", method: "get",class:"form-horizontal ", role:"form") do
            .col-xs-9.col-sm-10.col-md-10.col-lg-10
              = text_field_tag(:q,nil,placeholder:"Поиск...",class:" form-control")
            = submit_tag("Поиск",class:"btn btn-default col-xs-3 col-sm-2 col-md-2 col-lg-2")

app/views/inc/_logo.html.slim
header
  |  <img class="hidden-xs hidden-sm center-block" src = 
  = asset_path "logo.png"
  |  alt=""> 
  h1.text-center
    = InfoHelper::NAME_SITE

app/views/inc/_search.html.slim
.row
  .col-xs-12.col-sm-12.col-md-5.col-lg-4
        .dropdown.btn.col-xs-12.col-sm-12.col-md-6.col-lg-6
          - if signed_in?
            a.dropdown-toggle[href="#" data-toggle="dropdown"]
              |Профиль
              b.caret
            ul.dropdown-menu
              li
                = link_to 'Выйти', destroy_profile_session_path, :method => :delete
          - else
            a.dropdown-toggle[href="#" data-toggle="dropdown"]
              |Личный кабинет
              b.caret
            ul.dropdown-menu
              li = link_to 'Войти', new_profile_session_path
              li = link_to 'Зарегистрироваться', new_profile_registration_path
            a.btn.btn-primary.col-xs-12.col-sm-12.col-md-2.col-lg-2 [href=new_ad_url]
                      |Подать объявление