config/routes.rb
Rails.application.routes.draw do
  devise_for :profiles
  resources :ads
  resources :rubrics
  resources :properts
  get 'info/socket'

  get 'info/convention'

  get 'info/offer'

  root 'index#index'

  resources :cities

end

app/models/propert.rb
class Propert < ActiveRecord::Base
end

app/controllers/properts_controller.rb
class PropertsController < ApplicationController
  before_action :set_propert, only: [:show, :edit, :update, :destroy]

  # GET /properts
  # GET /properts.json
  def index
    @properts = Propert.all
  end

  # GET /properts/1
  # GET /properts/1.json
  def show
  end

  # GET /properts/new
  def new
    @propert = Propert.new
  end

  # GET /properts/1/edit
  def edit
  end

  # POST /properts
  # POST /properts.json
  def create
    @propert = Propert.new(propert_params)

    respond_to do |format|
      if @propert.save
        format.html { redirect_to @propert, notice: 'Propert was successfully created.' }
        format.json { render :show, status: :created, location: @propert }
      else
        format.html { render :new }
        format.json { render json: @propert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properts/1
  # PATCH/PUT /properts/1.json
  def update
    respond_to do |format|
      if @propert.update(propert_params)
        format.html { redirect_to @propert, notice: 'Propert was successfully updated.' }
        format.json { render :show, status: :ok, location: @propert }
      else
        format.html { render :edit }
        format.json { render json: @propert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properts/1
  # DELETE /properts/1.json
  def destroy
    @propert.destroy
    respond_to do |format|
      format.html { redirect_to properts_url, notice: 'Propert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_propert
      @propert = Propert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def propert_params
      params.require(:propert).permit(:code, :name, :value)
    end
end

app/helpers/properts_helper.rb
module PropertsHelper
end

app/views/properts/_form.html.slim
= form_for(@propert) do |f|
  - if @propert.errors.any?
    #error_explanation
      h2
        = pluralize(@propert.errors.count, "error")
        |  prohibited this propert from being saved:
      ul
        - @propert.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label :code
    br
    = f.text_field :code
  .field
    = f.label :name
    br
    = f.text_field :name
  .field
    = f.label :value
    br
    = f.text_field :value
  .actions
    = f.submit

app/views/properts/edit.html.slim
h1
  | Editing Propert
= render 'form'
= link_to 'Show', @propert
|  | 
= link_to 'Back', properts_path

app/views/properts/index.html.slim
p#notice
  = notice
h1
  | Listing Properts
table
  thead
    tr
      th
        | Code
      th
        | Name
      th
        | Value
      th[colspan="3"]
  tbody
    - @properts.each do |propert|
      tr
        td
          = propert.code
        td
          = propert.name
        td
          = propert.value
        td
          = link_to 'Show', propert
        td
          = link_to 'Edit', edit_propert_path(propert)
        td
          = link_to 'Destroy', propert, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Propert', new_propert_path

app/views/properts/new.html.slim
h1
  | New Propert
= render 'form'
= link_to 'Back', properts_path

app/views/properts/show.html.slim
p#notice
  = notice
p
  strong
    | Code:
  = @propert.code
p
  strong
    | Name:
  = @propert.name
p
  strong
    | Value:
  = @propert.value
= link_to 'Edit', edit_propert_path(@propert)
|  | 
= link_to 'Back', properts_path