config/routes.rb
Rails.application.routes.draw do
  devise_for :profiles
  resources :ads
  resources :rubrics
  resources :properts
  get 'info/socket'

  get 'info/convention'

  get 'info/offer'

  root 'index#index'

  resources :cities

end

app/models/rubric.rb
class Rubric < ActiveRecord::Base
  belongs_to :rubric
  has_many :ads
end

app/controllers/rubrics_controller.rb
class RubricsController < ApplicationController
  before_action :set_rubric, only: [:show, :edit, :update, :destroy]

  # GET /rubrics
  # GET /rubrics.json
  def index
    @rubrics = Rubric.all
  end

  # GET /rubrics/1
  # GET /rubrics/1.json
  def show
  end

  # GET /rubrics/new
  def new
    @rubric = Rubric.new
  end

  # GET /rubrics/1/edit
  def edit
  end

  # POST /rubrics
  # POST /rubrics.json
  def create
    @rubric = Rubric.new(rubric_params)

    respond_to do |format|
      if @rubric.save
        format.html { redirect_to @rubric, notice: 'Rubric was successfully created.' }
        format.json { render :show, status: :created, location: @rubric }
      else
        format.html { render :new }
        format.json { render json: @rubric.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rubrics/1
  # PATCH/PUT /rubrics/1.json
  def update
    respond_to do |format|
      if @rubric.update(rubric_params)
        format.html { redirect_to @rubric, notice: 'Rubric was successfully updated.' }
        format.json { render :show, status: :ok, location: @rubric }
      else
        format.html { render :edit }
        format.json { render json: @rubric.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rubrics/1
  # DELETE /rubrics/1.json
  def destroy
    @rubric.destroy
    respond_to do |format|
      format.html { redirect_to rubrics_url, notice: 'Rubric was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rubric
      @rubric = Rubric.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rubric_params
      params.require(:rubric).permit(:name, :nambe, :rubric_id)
    end
end

app/helpers/rubrics_helper.rb
module RubricsHelper
end

app/views/rubrics/_form.html.slim
= form_for(@rubric) do |f|
  - if @rubric.errors.any?
    #error_explanation
      h2
        = pluralize(@rubric.errors.count, "error")
        |  prohibited this rubric from being saved:
      ul
        - @rubric.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label :name
    br
    = f.text_field :name
  .field
    = f.label :nambe
    br
    = f.text_field :nambe
  .field
    = f.label :rubric_id
    br
    = f.text_field :rubric_id
  .actions
    = f.submit

app/views/rubrics/edit.html.slim
h1
  | Editing Rubric
= render 'form'
= link_to 'Show', @rubric
|  | 
= link_to 'Back', rubrics_path

app/views/rubrics/index.html.slim
p#notice
  = notice
h1
  | Listing Rubrics
table
  thead
    tr
      th
        | Name
      th
        | Nambe
      th
        | Rubric
      th[colspan="3"]
  tbody
    - @rubrics.each do |rubric|
      tr
        td
          = rubric.name
        td
          = rubric.nambe
        td
          = rubric.rubric
        td
          = link_to 'Show', rubric
        td
          = link_to 'Edit', edit_rubric_path(rubric)
        td
          = link_to 'Destroy', rubric, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Rubric', new_rubric_path

app/views/rubrics/new.html.slim
h1
  | New Rubric
= render 'form'
= link_to 'Back', rubrics_path

app/views/rubrics/show.html.slim
p#notice
  = notice
p
  strong
    | Name:
  = @rubric.name
p
  strong
    | Nambe:
  = @rubric.nambe
p
  strong
    | Rubric:
  = @rubric.rubric
= link_to 'Edit', edit_rubric_path(@rubric)
|  | 
= link_to 'Back', rubrics_path